// Generated by scripts/generate-runtime-config.mjs. Do not edit manually.
export const GENERATED_HTTP_RETRY_COUNT = 3;
export const GENERATED_HTTP_RETRY_INITIAL_DELAY_MS = 250;
export const GENERATED_HTTP_RETRY_MAX_DELAY_MS = 2000;
